### ISSUE TITLE
Unable to Return or Set Site Routes

### ISSUE THREAD

**Issue by jracek-chl** [aligent/bigcommerce-v3-api-php-client#144] opened 2022-07-27 23:15 UTC
It appears that the site routes portion of the library is missing. While an optional routes variable exists on the BigCommerce\ApiV3\ResourceModels\Channel\ChannelSite class, that routes variable is never set. A search of the library does not return an endpoint for /routes so I don't believe the data is ever being retrieved.

I can manually add a site route via the BigCommerce API using Postman and then verify that that site route is returned by https://api.bigcommerce.com/stores/{{store-hash}}/v3/sites/{{site-id}}/routes in Postman. 

The code below, which utilizes the Aligent library, throws a "Typed property BigCommerce\ApiV3\ResourceModels\Channel\ChannelSite::$routes must not be accessed before initialization" error:

$mySite = $api->channel($channel_id)->site($site_id)->get()->getSite();
$allRoutes = $mySite->routes;

Additionally, because a routes endpoint doesn't exist in the library, you cannot set a route and have that saved to BigCommerce. It feels like there should be a CHANNEL_SITE_ROUTES_ENDPOINT in the ChannelSite class and corresponding getRoutes() and createRoutes() methods within that class.

**Comment by jswift** [comment] 2022-08-05 00:56
These endpoints are relatively new, I'll quickly implement the routes one at least.

**Comment by jswift** [comment] 2022-08-05 05:05
I've made it `$api->sites()->routes()` because it matches the structure of the documentation, although Sites is an exact duplicate of channel -> sites.

**Comment by jswift** [comment] 2022-08-05 05:06
I might also make it accessible as `$api->channel()->sites()->routes()` for convenience

**Comment by jswift** [comment] 2022-08-16 03:49
Fixed in [1.9.0](https://github.com/aligent/bigcommerce-v3-api-php-client/releases/tag/v1.9.0)

**Closed by jswift** 2022-08-16 03:49 UTC
